
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb
  namespace: todo
  labels:
    io.kompose.service: mongodb
  annotations:
    environment: local

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
      annotations:
        environment: local
    spec:
      restartPolicy: Always
      containers:
        - image: docker.io/mongo:7-jammy
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbRootUsername
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbRootPassword
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbDatabase
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb

---

apiVersion: v1
kind: Service

metadata:
  name: mongodb
  namespace: todo
  labels:
    io.kompose.service: mongodb
  annotations:
    environment: local

spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 31000
  selector:
    io.kompose.service: mongodb
