
apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    app: todo
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.31.0 (HEAD)
    type: backend
  labels:
    io.kompose.service: todo
  name: todo

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo
  template:
    metadata:
      annotations:
        app: todo
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.version: 1.31.0 (HEAD)
        type: backend
      labels:
        io.kompose.service: todo
    spec:
      containers:
        - env:
            - name: bindAddress
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: bindAddress
            - name: mongodbUrl
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbUrl
          image: k3d.localhost:5000/todo
          name: todo
          ports:
            - containerPort: 2010
      restartPolicy: Always

---

apiVersion: v1
kind: Service

metadata:
  annotations:
    app: todo
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.31.0 (HEAD)
    type: todo
  labels:
    io.kompose.service: todo
  name: todo

spec:
  ports:
    - port: 3090
  selector:
    io.kompose.service: todo
