
apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo
  namespace: todo
  labels:
    io.kompose.service: todo
  annotations:
    app: todo
    type: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo
  template:
    metadata:
      labels:
        io.kompose.service: todo
      annotations:
        app: todo
        type: backend
    spec:
      containers:
        - env:
            - name: bindAddress
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: bindAddress
            - name: mongodbUrl
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbUrl
          image: k3d.localhost:5000/todo
          name: todo
          ports:
            - containerPort: 2010
      restartPolicy: Always

---

apiVersion: v1
kind: Service

metadata:
  name: todo
  namespace: todo
  labels:
    io.kompose.service: todo
  annotations:
    app: todo
    type: backend

spec:
  ports:
    - port: 3090
  selector:
    io.kompose.service: todo
