
apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo
  namespace: todo
  labels:
    io.kompose.service: todo
  annotations:
    app: todo
    type: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo
  template:
    metadata:
      labels:
        io.kompose.service: todo
      annotations:
        app: todo
        type: backend
    spec:
      restartPolicy: Always
      containers:
        - image: docker.io/jamming/todo:1.0.0
          name: todo
          env:
            - name: BIND_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: bindAddress
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: mongodbUrl
          ports:
            - containerPort: 2010

---

apiVersion: v1
kind: Service

metadata:
  name: todo
  namespace: todo
  labels:
    io.kompose.service: todo
  annotations:
    app: todo
    type: backend

spec:
  ports:
    - port: 2010
  selector:
    io.kompose.service: todo
