
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb
  namespace: todo
  labels:
    io.kompose.service: mongodb

spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 100Mi
