package com.hexagonkt.todokt.backend

import com.hexagonkt.http.server.Server
import com.hexagonkt.http.server.jetty.JettyServletAdapter
import com.hexagonkt.store.mongodb.MongoDbStore
import com.hexagonkt.templates.pebble.PebbleAdapter
import com.hexagonkt.todokt.backend.TaskPriority.NORMAL
import com.hexagonkt.web.template
import java.time.LocalDateTime

/**
 * Task priority.
 */
enum class TaskPriority { HIGH, NORMAL, LOW }

/**
 * Task entity.
 */
data class Task(
    val code: String,
    val name: String,
    val labels: List<String> = emptyList(),
    val context: List<String> = emptyList(),
    val priority: TaskPriority = NORMAL,
    val createdAt: LocalDateTime = LocalDateTime.now(),
    val completedAt: LocalDateTime? = null,
    val deletedAt: LocalDateTime? = null
)

/** Store for tasks. */
val store = MongoDbStore(Task::class, Task::code, "")

fun main(vararg args: String) {
    val server = Server(JettyServletAdapter()) {
        // Serves 'resources/public' classpath folder from servers root '/'
        assets("public")

        // Renders index page from Pebble template. SPA which code is generated by Frontend module
        get {
            template(PebbleAdapter, "index.html")
        }

        path("/tasks") {
            get {}
            post {}
            delete {}
        }
    }

    server.start()
}
